# Generated by Django 3.2.6 on 2021-09-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0002_auto_20210910_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_type',
            field=models.BooleanField(default=True),
        ),
    ]
