# Generated by Django 3.2.6 on 2021-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0003_alter_registration_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_type',
            field=models.BooleanField(default=False),
        ),
    ]
